// "The story behind it": a short, factual background note for every quote in
// quotes.js, keyed by quote id. Keep each to two or three plain sentences:
// who said it, where and when, and what was going on.
window.STORIES = {
  "seneca-postpone": "Seneca opens his very first letter to his friend Lucilius with this warning. He wrote the letters around 65 AD, after retiring from years as adviser to Emperor Nero, and the whole letter is about time being the only thing we truly own.",
  "eroosevelt-cannot": "Eleanor Roosevelt wrote this in You Learn by Living, a book of life lessons she published at 76. She had been painfully shy as a young woman and said she built her confidence by doing, one by one, the things that frightened her.",
  "troosevelt-whatyouhave": "In his 1913 autobiography, Theodore Roosevelt says he heard this from Squire Bill Widener of Widener's Valley, Virginia. Roosevelt called it the best summary of practical duty he knew.",
  "jobs-hungry": "Steve Jobs ended his 2005 Stanford graduation speech with these words. They were printed on the back cover of the final issue of the Whole Earth Catalog in 1974, a counterculture magazine Jobs loved as a teenager.",
  "jobs-time": "This comes from the part of Jobs's 2005 Stanford speech about death. A year earlier he had been diagnosed with pancreatic cancer, and he told the students that remembering he would die was the best tool he knew for making big choices.",
  "gretzky-shots": "Wayne Gretzky, hockey's all-time leading scorer, said this in 1983 when Hockey News editor Bob McKenzie asked why he shot so often. That season he scored 71 goals.",
  "thoreau-dreams": "This line is from the conclusion of Walden. From 1845 to 1847 Thoreau lived in a small cabin he built himself beside Walden Pond in Massachusetts, as an experiment in living simply and on purpose.",
  "oliver-wild": "These are the closing lines of \"The Summer Day\". The poet watches a grasshopper eating sugar from her hand, admits she doesn't know exactly what a prayer is, but does know how to pay attention, and then turns the question to the reader.",
  "clear-systems": "James Clear's Atomic Habits (2018) argues that results come from small daily routines, not from big goals. This line sums up the book's first chapter, and the book has sold over 20 million copies.",
  "durant-habit": "This is usually credited to Aristotle, but the words are Will Durant's. In The Story of Philosophy (1926) he used them to sum up Aristotle's idea, from the Nicomachean Ethics, that character is built by repeated action.",
  "aurelius-beone": "Marcus Aurelius was Roman emperor from 161 to 180 AD. Meditations was his private notebook, written in Greek largely during military campaigns, and never meant for anyone else to read.",
  "mlk-moving": "Martin Luther King Jr. said this to students at Spelman College in Atlanta in April 1967, a year before he was killed. He was urging them to keep working for justice even when progress felt slow.",
  "tolkien-time": "Gandalf says this to Frodo in the Mines of Moria, when Frodo wishes the Ring had never come to him. Tolkien wrote most of the book during and after World War II.",
  "seneca-imagination": "From Seneca's 13th letter to Lucilius, which is about fear. He advises checking whether a trouble is actually happening, or only expected, because most of what we dread never arrives.",
  "epictetus-opinions": "Epictetus was born a slave in the Roman Empire around 50 AD and later became a famous teacher. His student Arrian wrote down his lessons, and this is from the Enchiridion, a pocket handbook of them.",
  "aurelius-little": "Another note to himself from the emperor's private notebook, Meditations (Book 7). He ruled the most powerful empire on Earth and still reminded himself that contentment comes from how you think.",
  "lamott-unplug": "Anne Lamott shared this in her 2017 TED talk \"12 truths I learned from life and writing\". The talk lists what she had learned from decades of writing, recovery and raising a son, and this is its most quoted line.",
  "tolstoy-patience": "In War and Peace, General Kutuzov says this as the Russian army faces Napoleon's invasion in 1812. Instead of risking everything in battle, he waited, and the French army eventually wore itself out and retreated.",
  "dillard-days": "From The Writing Life (1989), Annie Dillard's short book about the daily work of writing. She argues that a schedule shapes a life, because the small hours add up to the whole.",
  "watts-dance": "Alan Watts was a British writer who introduced Eastern philosophy to Western readers. In The Wisdom of Insecurity (1951) he argued that chasing total security only makes us more anxious.",
  "lee-water": "Bruce Lee said this playing a martial-arts teacher in a 1971 episode of the TV series Longstreet. The words were his own philosophy, and he repeated them in an interview the same year.",
  "saunders-plans": "Many people know this from John Lennon's 1980 song \"Beautiful Boy\", but cartoonist Allen Saunders published it in Reader's Digest in 1957.",
  "lorde-care": "Audre Lorde wrote this in A Burst of Light (1988), essays from the years she lived with cancer. As a Black lesbian poet and activist, she argued that looking after yourself is strength, not selfishness.",
  "rogers-like": "Fred Rogers closed many episodes of Mister Rogers' Neighborhood (1968 to 2001) by telling children this. He believed every child needed to hear that they were valued just as they were.",
  "frost-through": "From \"A Servant to Servants\" (1914), a poem in the voice of an overworked farm wife. She says she sees no way out of her hard life except to keep going through it.",
  "alcott-storms": "Amy March says this in Little Women (1868). Alcott based the novel on growing up with her three sisters during hard times in Massachusetts.",
  "beckett-fail": "From Worstward Ho (1983), one of Samuel Beckett's last works. In the original it is quite bleak, but athletes and start-up founders adopted it as a motto about learning from failure.",
  "jordan-shots": "From a 1997 Nike advert. Before this line, Michael Jordan lists the 9,000 shots he missed and the 26 times he was trusted with the game-winning shot and missed.",
  "troosevelt-arena": "Theodore Roosevelt said this at the Sorbonne in Paris in April 1910, a year after leaving the presidency. Known as \"The Man in the Arena\", it praises the person who tries over the critic who doesn't.",
  "gandhi-will": "Gandhi wrote this in his weekly newspaper Young India in August 1920, in an essay called \"The Doctrine of the Sword\". He was explaining why nonviolence takes more courage than violence.",
  "seneca-live": "From Seneca's 78th letter, written while he was struggling with illness. He tells Lucilius that holding on through a hard time is itself a brave and worthwhile act.",
  "camus-summer": "From \"Return to Tipasa\" (1952), an essay about Camus revisiting Roman ruins in Algeria, where he grew up, after the dark years of World War II.",
  "dickinson-hope": "Emily Dickinson wrote nearly 1,800 poems but published fewer than a dozen in her lifetime. This one was found among her papers after she died in 1886.",
  "tagore-dawn": "Rabindranath Tagore, the first non-European to win the Nobel Prize in Literature (1913), wrote the short poems in Fireflies after travelling in China and Japan, where he saw thoughts written on fans and silk.",
  "keller-overcoming": "Helen Keller lost her sight and hearing at 19 months old. She wrote this essay, Optimism, in 1903 while studying at Radcliffe College, which she went on to graduate from.",
  "nietzsche-why": "From Twilight of the Idols (1889), in a section of short sayings. Viktor Frankl later quoted it to explain why prisoners who still had something to live for were more likely to survive the Nazi camps.",
  "murakami-storm": "From Kafka on the Shore (2002). An inner voice called \"the boy named Crow\" says this to Kafka, a 15-year-old who has run away from home.",
  "brown-story": "Brené Brown is a researcher at the University of Houston who studies shame and courage. This is from The Gifts of Imperfection (2010), her guide to accepting yourself as you are.",
  "curie-understand": "Marie Curie is the only person to win Nobel Prizes in two different sciences, physics and chemistry. This line is widely credited to her, and the earliest printed source is a 1973 book, so treat it as attributed.",
  "baldwin-faced": "James Baldwin wrote this in a 1962 New York Times essay, \"As Much Truth As One Can Bear\". He was arguing that writers, and the country, had to look honestly at America's problems before they could fix them.",
  "frankl-attitude": "Viktor Frankl was an Austrian psychiatrist who survived Auschwitz and other Nazi camps. He wrote Man's Search for Meaning in nine days in 1946, describing how even there, prisoners kept the freedom to choose their attitude.",
  "frankl-change": "From the second half of Man's Search for Meaning, where Frankl explains logotherapy, his approach to helping people find meaning when circumstances can't be changed.",
  "aurelius-obstacle": "In Meditations (5.20), Marcus Aurelius was writing about difficult people: whatever gets in your way becomes your chance to practise patience. Ryan Holiday's 2014 book The Obstacle Is the Way is built on this line.",
  "socrates-examined": "Socrates said this at his trial in Athens in 399 BC, as recorded by his student Plato. Rather than promise to stop asking questions, he accepted a death sentence.",
  "rilke-questions": "In 1903 a 19-year-old military cadet, Franz Kappus, sent Rilke his poems and asked for advice. Rilke's ten replies were published in 1929 as Letters to a Young Poet.",
  "gibran-shell": "From The Prophet (1923), in which a wise man leaving a city answers people's questions about love, work, pain and joy. It has been translated into over 100 languages.",
  "emerson-trust": "From Emerson's 1841 essay \"Self-Reliance\", which urges people to trust their own judgement instead of following the crowd. It became a founding text of American individualism.",
  "tagore-errors": "From Stray Birds (1916), a book of very short poems Tagore published in 1916, the year he visited Japan. Many are only one or two lines long.",
  "dumbledore-choices": "Dumbledore says this to Harry at the end of Chamber of Secrets. Harry is worried he is too much like Voldemort, because the Sorting Hat almost put him in Slytherin.",
  "seneca-company": "From Seneca's 7th letter, about avoiding crowds. He tells Lucilius that we absorb the habits of the people around us, so choose them carefully.",
  "aurelius-right": "A short rule the emperor wrote for himself in Meditations (12.17), the last book of his private notebook.",
  "epictetus-master": "One of the sayings of Epictetus preserved by later writers, not in his main books. He had been a slave himself, so he knew that real freedom starts with self-control.",
  "keller-together": "Recorded by Joseph Lash in Helen and Teacher (1980), a biography of Helen Keller and her teacher Anne Sullivan. Their partnership lasted almost 50 years.",
  "brown-connection": "From Brené Brown's 2010 TEDx talk in Houston, \"The power of vulnerability\". It became one of the most-watched TED talks ever.",
  "angelou-rainbow": "Maya Angelou used this line often in talks and in Letter to My Daughter (2008), her book of short essays. She meant: be the person who brings a bit of hope into someone else's bad day.",
  "aesop-kindness": "The moral of Aesop's fable \"The Lion and the Mouse\". A lion spares a tiny mouse, and later the mouse frees the lion by gnawing through a hunter's net. Aesop was a storyteller in ancient Greece around 600 BC.",
  "dalai-compassion": "From The Art of Happiness (1998), written by American psychiatrist Howard Cutler from his conversations with the Dalai Lama about everyday happiness.",
  "brown-vulnerability": "From Brené Brown's 2012 TED talk \"Listening to shame\", her follow-up to her famous talk on vulnerability.",
  "mandela-courage": "From Long Walk to Freedom (1994), Nelson Mandela's autobiography. He began writing it in secret during his 27 years in prison, and it came out the year he became South Africa's president.",
  "leguin-journey": "From The Left Hand of Darkness (1969), Le Guin's novel about a human envoy on an icy planet. The line comes near the end, after a long crossing of a glacier.",
  "plath-iam": "From The Bell Jar (1963), Sylvia Plath's only novel, drawn from her own depression at 20. In this moment the narrator listens to her heartbeat and hears proof that she is still here.",
  "morrison-write": "Toni Morrison said this in a 1981 speech to the Ohio Arts Council. She wrote her first novel, The Bluest Eye, early in the morning before her job as a book editor, while raising two sons.",
  "nemo-swim": "In Pixar's Finding Nemo (2003), Dory, a fish with short-term memory loss, sings this to Marlin as they cross the ocean searching for his son. She can't remember much, but she never stops.",
  "tolkien-door": "In The Fellowship of the Ring, Frodo remembers his uncle Bilbo saying this as he sets out from the Shire. Bilbo used to say that every road leads to the Great Road, and from there, anywhere.",
  "angelou-reduced": "From Letter to My Daughter (2008), written when Maya Angelou was 80. She had survived trauma as a child and stopped speaking for five years, and wrote this as advice to the daughters she never had.",
  "lubbock-rest": "John Lubbock was a British banker, scientist and politician who created Britain's bank holidays in 1871, giving workers their first official days off. This is from his 1894 book The Use of Life.",
  "proverb-seven": "A Japanese proverb, nana korobi ya oki. It is linked to Daruma dolls, round-bottomed toys that always roll back upright when knocked over, and are a popular good-luck gift for new goals."
};
