#!/usr/bin/env python3
"""Move finished pick batches into permanent monthly archive files.

Every batch ever published is kept. Batches whose window ended more than
ARCHIVE_AFTER_DAYS ago are moved, together with their final scoring from
data/prices.js, out of data/picks.js into data/archive/<YYYY-MM>.js (month of
the batch date). data/archive/index.js lists every archived batch with small
per-market summary stats, so the page can show the whole history without
downloading every month; a month's file is only loaded when someone opens it.

Safe to run repeatedly: batches already archived are merged, never duplicated.

Usage:  python scripts/archive.py
"""
from __future__ import annotations

import datetime as dt
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
ARCHIVE = DATA / "archive"
PICKS_JS = DATA / "picks.js"
PRICES_JS = DATA / "prices.js"
INDEX_JS = ARCHIVE / "index.js"
ARCHIVE_AFTER_DAYS = 45


def read_assigned(path: pathlib.Path, marker: str) -> dict:
    """Return the JSON object assigned right after `marker` in a .js file."""
    text = path.read_text(encoding="utf-8")
    start = text.index("{", text.index(marker))
    return json.loads(text[start: text.rindex("}") + 1])


def split_header(path: pathlib.Path, marker: str) -> str:
    text = path.read_text(encoding="utf-8")
    return text[: text.index(marker)]


def write_js(path: pathlib.Path, header: str, assignment: str, obj: dict) -> None:
    path.write_text(f"{header}{assignment}{json.dumps(obj, indent=2, ensure_ascii=False)};\n", encoding="utf-8")


def month_path(month: str) -> pathlib.Path:
    return ARCHIVE / f"{month}.js"


def load_month(month: str) -> dict:
    path = month_path(month)
    if not path.exists():
        return {"batches": [], "tracking": {}}
    return read_assigned(path, f'window.ARCHIVE["{month}"] = ')


def save_month(month: str, data: dict) -> None:
    data["batches"].sort(key=lambda b: (b["date"], b["id"]), reverse=True)
    header = ("// Generated by scripts/archive.py. Finished batches for this month with\n"
              "// their final results. Kept permanently; do not edit by hand.\n"
              "window.ARCHIVE = window.ARCHIVE || {};\n")
    write_js(month_path(month), header, f'window.ARCHIVE["{month}"] = ', data)


def market_stats(batch: dict, tracking: dict) -> dict:
    """Per-market numbers the page needs for summary tiles (mirrors index.html)."""
    out: dict[str, dict] = {}
    for p in batch["picks"]:
        m = out.setdefault(p["market"], {"n": 0, "priced": 0, "finished": 0, "hits": 0,
                                         "sumExpected": 0.0, "sumCloseRet": 0.0})
        m["n"] += 1
        m["sumExpected"] += (p["target"] / p["refPrice"] - 1) * 100
        t = tracking.get(p["yahoo"])
        if not t:
            continue
        close = t.get("periodClose", t.get("markPrice"))
        if close is None:
            continue
        final = t.get("periodFinal", t.get("status") != "Open")
        hit = t.get("targetHit", t.get("status") == "Target hit")
        m["priced"] += 1
        m["sumCloseRet"] += (close / p["refPrice"] - 1) * 100
        if final or hit:
            m["finished"] += 1
            m["hits"] += 1 if hit else 0
    for m in out.values():
        m["sumExpected"] = round(m["sumExpected"], 4)
        m["sumCloseRet"] = round(m["sumCloseRet"], 4)
    return out


def rebuild_index() -> dict:
    months = []
    for path in sorted(ARCHIVE.glob("????-??.js"), reverse=True):
        month = path.stem
        data = load_month(month)
        months.append({"month": month, "batches": [
            {"id": b["id"], "horizon": b.get("horizon", "monthly"), "date": b["date"],
             "expires": b["expires"], "markets": market_stats(b, data["tracking"].get(b["id"], {}))}
            for b in data["batches"]]})
    index = {"months": months}
    header = ("// Generated by scripts/archive.py: every archived batch, newest month first.\n")
    write_js(INDEX_JS, header, "window.ARCHIVE_INDEX = ", index)
    return index


def main() -> int:
    ARCHIVE.mkdir(parents=True, exist_ok=True)
    picks = read_assigned(PICKS_JS, "window.PICKS = ")
    prices = read_assigned(PRICES_JS, "window.PRICES = ") if PRICES_JS.exists() else {"tracking": {}}
    tracking = prices.setdefault("tracking", {})
    cutoff = (dt.date.today() - dt.timedelta(days=ARCHIVE_AFTER_DAYS)).isoformat()

    keep, moved = [], {}
    for batch in picks["batches"]:
        if batch["expires"] < cutoff:
            moved.setdefault(batch["date"][:7], []).append(batch)
        else:
            keep.append(batch)

    for month, batches in moved.items():
        data = load_month(month)
        existing = {b["id"] for b in data["batches"]}
        for b in batches:
            if b["id"] not in existing:
                data["batches"].append(b)
            data["tracking"][b["id"]] = tracking.pop(b["id"], data["tracking"].get(b["id"], {}))
        save_month(month, data)
        print(f"archived {len(batches)} batch(es) into data/archive/{month}.js")

    if moved:
        picks["batches"] = keep
        write_js(PICKS_JS, split_header(PICKS_JS, "window.PICKS = "), "window.PICKS = ", picks)
        write_js(PRICES_JS, split_header(PRICES_JS, "window.PRICES = "), "window.PRICES = ", prices)

    index = rebuild_index()
    total = sum(len(m["batches"]) for m in index["months"])
    print(f"archive: {total} batch(es) across {len(index['months'])} month file(s); "
          f"{len(keep)} active batch(es) in data/picks.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
